//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhinoPythonNetEditor.Component {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RhinoPythonNetEditor.Component.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {C62D29C7-F213} {7F0A2DDA-D43D} = default({C62D29C7-F213});
        ///    if (inputs[{C9474A41-931A}] != null)
        ///    {
        ///      {7F0A2DDA-D43D} = ({C62D29C7-F213})(inputs[{C9474A41-931A}]);
        ///    } 的本地化字符串。
        /// </summary>
        internal static string CS_InputParamItem_Template {
            get {
                return ResourceManager.GetString("CS_InputParamItem_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List&lt;{C62D29C7-F213}&gt; {7F0A2DDA-D43D} = null;
        ///    if (inputs[{C9474A41-931A}] != null)
        ///    {
        ///      {7F0A2DDA-D43D} = GH_DirtyCaster.CastToList&lt;{C62D29C7-F213}&gt;(inputs[{C9474A41-931A}]);
        ///    } 的本地化字符串。
        /// </summary>
        internal static string CS_InputParamList_Template {
            get {
                return ResourceManager.GetString("CS_InputParamList_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTree&lt;{C62D29C7-F213}&gt; {7F0A2DDA-D43D} = null;
        ///    if (inputs[{C9474A41-931A}] != null)
        ///    {
        ///      {7F0A2DDA-D43D} = GH_DirtyCaster.CastToTree&lt;{C62D29C7-F213}&gt;(inputs[{C9474A41-931A}]);
        ///    } 的本地化字符串。
        /// </summary>
        internal static string CS_InputParamTree_Template {
            get {
                return ResourceManager.GetString("CS_InputParamTree_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 abstract        ///\nas        ///\nbase        ///\nbool        ///\nbreak        ///\nbyte        ///\ncase        ///\ncatch        ///\nchar        ///\nchecked        ///\nclass        ///\nconst        ///\ncontinue        ///\ndecimal        ///\ndefault        ///\ndelegate        ///\ndo        ///\ndouble        ///\nelse        ///\nenum        ///\nevent        ///\nexplicit        ///\nextern        ///\nfalse        ///\nfinally        ///\nfixed        ///\nfloat        ///\nfor        ///\nforeach        ///\ngoto        ///\nif        ///\nimplicit        ///\nin        ///\nint        ///\ninterface        ///\ninternal        ///\nis        ///\nlock        ///\nlong        ///\nnamespace        ///\nnew        ///\nnull        ///\nobject        ///\noperator        ///\nout        ///\noverride        ///\nparams        ///\nprivate        ///\nprotected        ///\npublic        ///\nreadonly        ///\nref        ///\nreturn        ///\nsbyte        ///\nsealed        ///\nshort        ///\nsizeof        ///\nstackalloc        ///\nstatic        ///\nstring        ///\nst [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CS_LanguageKeywords {
            get {
                return ResourceManager.GetString("CS_LanguageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if ({7F0A2DDA-D43D} != null)
        ///      {
        ///        if (GH_Format.TreatAsCollection({7F0A2DDA-D43D}))
        ///        {
        ///          IEnumerable __enum_{7F0A2DDA-D43D} = (IEnumerable)({7F0A2DDA-D43D});
        ///          DA.SetDataList({C9474A41-931A}, __enum_{7F0A2DDA-D43D});
        ///        }
        ///        else
        ///        {
        ///          if ({7F0A2DDA-D43D} is Grasshopper.Kernel.Data.IGH_DataTree)
        ///          {
        ///            //merge tree
        ///            DA.SetDataTree({C9474A41-931A}, (Grasshopper.Kernel.Data.IGH_DataTree)({7F0A2DDA-D43D}));
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CS_OutputParam_Template {
            get {
                return ResourceManager.GetString("CS_OutputParam_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PythonIcon {
            get {
                object obj = ResourceManager.GetObject("PythonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using Grasshopper.Kernel;
        ///using Python.Runtime;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Collections;
        ///using Rhino;
        ///using Rhino.Geometry;
        ///using Grasshopper;
        ///using Grasshopper.Kernel.Data;
        ///using Grasshopper.Kernel.Types;
        ///using Grasshopper.Kernel.Parameters;
        ///
        ///  public class PythonScriptInstance : GH_ScriptInstance
        ///    {
        ///        public List&lt;string&gt; __err = new List&lt;string&gt;();
        ///        public List&lt;string&gt; __o [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
